/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfaceelevador;

import java.util.concurrent.TimeUnit;

/**
 *
 * @author USER
 */

public class InterfaceElevador extends javax.swing.JFrame{

    /**
     * Creates new form InterfaceElevador
     */
    private SystemElevador SystemElevador;


    public InterfaceElevador() {
        initComponents();
        setLocationRelativeTo(null);
        SystemElevador = new SystemElevador();
        updateAndarLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_andar3 = new javax.swing.JButton();
        btn_andar2 = new javax.swing.JButton();
        btn_andar1 = new javax.swing.JButton();
        btn_terreo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_mostrarAndar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Elevador");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoDentro.jpg"))); // NOI18N

        btn_andar3.setText("Andar 3");
        btn_andar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_andar3ActionPerformed(evt);
            }
        });

        btn_andar2.setText("Andar 2");
        btn_andar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_andar2ActionPerformed(evt);
            }
        });

        btn_andar1.setText("Andar 1");
        btn_andar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_andar1ActionPerformed(evt);
            }
        });

        btn_terreo.setText("Terreo");
        btn_terreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_andar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_andar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_andar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_terreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_andar3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_andar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_andar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_terreo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_mostrarAndar.setText("0");

        jLabel2.setText("Você está no Andar:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lbl_mostrarAndar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_mostrarAndar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateAndarLabel() {
        String andar = String.valueOf(SystemElevador.getAndar());
        if (andar.equals("0")) andar = "Térreo";
        lbl_mostrarAndar.setText(andar);
    }
    

    private void animacaoPortaFechando() {
        Thread t1 = new Thread() {
            public void run() { 
                try {
                    Thread.sleep(200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoportafechada1.jpg")));             
                } catch (Exception e) {}
                try {
                    Thread.sleep(200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoportafechada2.jpg")));   
                } catch (Exception e) {}
                try {
                    Thread.sleep(200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoportafechada3.jpg")));         
                } catch (Exception e) {}
                try {
                    Thread.sleep(200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoportafechada4.jpg")));           
                } catch (Exception e) {}
                try {
                    Thread.sleep(200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoportafechada5.jpg")));           
                } catch (Exception e) {}
                try {
                    Thread.sleep(200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoportafechadatotal.jpg")));
                } catch (Exception e) {}
            }
        };
        t1.start();
    }
    private void animacaoPortaAbrindo() {
        Thread t1 = new Thread() {
            public void run() { 
                try {
                    Thread.sleep(200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoportafechadatotal.jpg")));
                } catch (Exception e) {}
                try {
                    Thread.sleep(200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoportafechada5.jpg")));           
                } catch (Exception e) {}
                try {
                    Thread.sleep(200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoportafechada4.jpg")));           
                } catch (Exception e) {}
                try {
                    Thread.sleep(200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoportafechada3.jpg")));         
                } catch (Exception e) {}
                try {
                    Thread.sleep(200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoportafechada2.jpg")));   
                } catch (Exception e) {}
                try {
                    Thread.sleep(200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoportafechada1.jpg")));             
                } catch (Exception e) {}
                try {
                    Thread.sleep(200);
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visaoDentro.jpg")));        
                } catch (Exception e) {}
            }
        };
        t1.start();
    }

    private void btn_andar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_andar3ActionPerformed
        animacaoPortaFechando();
        SystemElevador.elevador(3);
        animacaoPortaAbrindo();
        updateAndarLabel();
    }//GEN-LAST:event_btn_andar3ActionPerformed

    private void btn_andar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_andar2ActionPerformed
        animacaoPortaFechando();
        SystemElevador.elevador(2);
        animacaoPortaAbrindo();
        updateAndarLabel();
    }//GEN-LAST:event_btn_andar2ActionPerformed

    private void btn_andar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_andar1ActionPerformed
        animacaoPortaFechando();
        SystemElevador.elevador(1);
        animacaoPortaAbrindo();
        updateAndarLabel();
    }//GEN-LAST:event_btn_andar1ActionPerformed

    private void btn_terreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terreoActionPerformed
        animacaoPortaFechando();
        SystemElevador.elevador(0);
        animacaoPortaAbrindo();
        updateAndarLabel();
    }//GEN-LAST:event_btn_terreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceElevador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_andar1;
    private javax.swing.JButton btn_andar2;
    private javax.swing.JButton btn_andar3;
    private javax.swing.JButton btn_terreo;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_mostrarAndar;
    // End of variables declaration//GEN-END:variables
}